# Usa la imagen de Node.js 14 (o la versión que necesites)
FROM node:18-alpine
# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app
# Copia el package.json y package-lock.json al contenedor
COPY package.json package-lock.json ./

# Instala las dependencias
RUN npm install
# Copia el resto de los archivos de la aplicación al contenedor
COPY . .
ENV PUBLIC_API_PROXY=${PUBLIC_API_PROXY}

EXPOSE 4000
# Ejecuta el comando para iniciar el servidor de desarrollo o producción
CMD ["npm" , "run" , "dev" , "--" , "--host" ,"--port","4000"]